In [1]:
import tkinter as tk
from tkinter import filedialog
import numpy as np
import moviepy.editor as mp
from pydub import AudioSegment
import wave

root = tk.Tk()
root.withdraw()
file_path = filedialog.askopenfilename()
if file_path==():
    exit()

#write audiofile
clip = mp.VideoFileClip(file_path)
clip.audio.write_audiofile("Gehen-6,5.wav")


MoviePy - Writing audio in Gehen-6,5.wav


MoviePy - Done.


In [10]:

import tkinter as tk
from tkinter import filedialog
import numpy as np
import moviepy.editor as mp
from pydub import AudioSegment
import wave
#mp3 to wav
#AudioSegment.from_mp3("Gehen-6,5.mp3").export("Gehen-6,5.wav", format="wav")

#wav loudest point
w = wave.open('Gehen-6,5-1.wav')
sam = w.readframes(w.getnframes())
sam = np.frombuffer(sam, dtype=np.int16)

bigpos = np.where( sam > 10000 )
bigpos_2 = np.where(np.argmax(sam))

In [11]:
print(bigpos_2)
print(bigpos)

(array([0]),)
(array([158570, 158572, 158574, 158577, 158579, 158586, 158598, 158603,
       158605, 158617, 158619, 158621, 158735, 158737, 158739, 158741,
       158743, 158745, 158747, 158748, 158749, 158750, 158751, 158752,
       158753, 158754, 158755, 158756, 158757, 158758, 158759, 158760,
       158761, 158762, 158764, 158774, 158776, 158781, 158826, 158845,
       158857, 158859, 158861, 158959, 158961, 158962, 158963, 158964,
       158965, 158966, 158967, 158968, 158969, 158970, 158971, 158972,
       158973, 158975, 158982, 158984, 158986, 158988, 159136, 159210]),)


In [6]:
import soundfile as sf
import pyloudnorm as pyln

data, rate = sf.read("Gehen-6,5.wav")
meter = pyln.Meter(rate) #
loudness = meter.integrated_loudness(data)
print(loudness)

-33.071804503246184


In [8]:
import cv2
import tkinter as tk
from tkinter import filedialog
import numpy as np
import moviepy.editor as mp
from pydub import AudioSegment
import wave
import numpy as np

root = tk.Tk()
root.withdraw()
file_path = filedialog.askopenfilename()
if file_path==():
    exit()

#write audiofile
clip = mp.VideoFileClip(file_path)
clip.audio.write_audiofile("Gehen-6,5-1.wav")

#mp3 to wav
#AudioSegment.from_mp3("Gehen-6,5_1.mp3").export("Gehen-6,5_1.wav", format="wav")

#wav loudest point
w = wave.open('Gehen-6,5-1.wav')
sam = w.readframes(w.getnframes())
sam = np.frombuffer(sam, dtype=np.int16)

bigpos = np.argmax(sam)

# import soundfile as sf
# import pyloudnorm as pyln

# data, rate = sf.read("file.wav")
# meter = pyln.Meter(rate) #
# loudness = meter.integrated_loudness(data)
# print(loudness)

MoviePy - Writing audio in Gehen-6,5-1.wav


MoviePy - Done.


In [13]:
bigpos = np.argmax(sam)

In [17]:
sam

array([  524,   512,   898, ..., -1330, -1627, -1279], dtype=int16)

In [14]:
print(bigpos)

158603


In [10]:
import soundfile as sf
import pyloudnorm as pyln

data, rate = sf.read("file_1.wav")
meter = pyln.Meter(rate) #
loudness = meter.integrated_loudness(data)
print(loudness)

-34.47555740501685


In [12]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.wavfile import read, write
from IPython.display import Audio
from numpy.fft import fft, ifft
%matplotlib inline


ModuleNotFoundError: No module named 'scipy.wavfile'

In [ ]:
Fs, data = read()